### PR TITLE
clone from my portfolio repository and copy it to my github pages

### PR DESCRIPTION
**Pull request by fickryiman**
- Update readme as well for live demo and descriptions

### CODE REVIEW

**Review by AlphaNtihinduka — COMMENTED** [review]
Hi @fickryiman ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
# Invalid Code Review Request

You have submitted a project with a readme file that is not detailed. Kindly edit and customize your readme with the project information for it to be professional.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray

Cheers and Happy coding!clapclapclap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by fickryiman** [comment]
my correct readme is on this branch, not in main branch, otherwise, I have to update my readme on main branch

**Review by Lizdev-05 — CHANGES_REQUESTED** [review]
Hi @fickryiman, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

## Required Changes ♻️
- Kindly check the live link provided in your README file, it is not leading to your portfolio instead, it is leading back to the README file, Kindly check your build and correct this.  🥺 💪 
- Kindly check this [link](https://www.w3schools.com/git/git_remote_pages.asp?remote=github) on how to deploy you application on gitHub. 🥺 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fickryiman** [comment]
Hi @Lizdev-05 ,

The live demo link will be updated once it has merge.
Do you want me to merge it first ?

**Pull request merged**
